### PR TITLE
Truncate RuboCops configuration and bump RuboCop and Reek.

### PR DESCRIPTION
**Pull request by troessner**
Retry from my botched [106](https://github.com/whitesmith/rubycritic/pull/106) pull request:

This pull request fixes several issues:

1.) Before this PR our rubocop.yml was huge. This is just plain wrong. The point of a styleguide is to have as minimal deviations as possible. Otherwise you can just drop the whole damn thing since it's more confusing than helpful. I kind of slimmed it down to the bare minimum. 
~~2.) I fixed 98% of all problems (or in most cases: let Rubocop fix it) that arose from [1] for everything **but lib/** and created a rubocop_todo.yml we need to fix in the future. The reason that I excluded lib/ was that the autocorrections from RuboCop on this folder made our features fail. I'll look into this separately in another pull request. I think we can live with this for now in order to get the updates out and fix that later.~~
3.) I bumped RuboCop to 0.36 which is the latest version that is running the latest parser which will give us Ruby 2.3 compatibility, at least for the tools that depend on parser (like Reek)
4.) I bumped Reek to 3.9 which is the latest version that is running the latest parser

P.S.: I know this PR looks huge but most changes are trivial like ' vs " so let's get this bad boy reviewed!

### CODE REVIEW

**Comment by nijikon** [comment]
Nice work!

**Comment by troessner** [comment]
Update regarding:

>> 2.) I fixed 98% of all problems (or in most cases: let Rubocop fix it) that arose from [1] for everything but lib/ and created a rubocop_todo.yml we need to fix in the future. The reason that I excluded lib/ was that the autocorrections from RuboCop on this folder made our features fail. I'll look into this separately in another pull request. I think we can live with this for now in order to get the updates out and fix that later.

I did fix lib/ and updated this PR accordingly. Now .rubocop_todo.yml is tiny with only a handful of exceptions which I'll fix separately in another PR.

**Comment by Onumis** [comment]
Looks great!
I was thinking of releasing this in a v2.6.1, but now I've introduced conficts :see_no_evil:

**Comment by troessner** [comment]
Sec, rebasing....

**Comment by troessner** [comment]
Fixed the conflicts, now let's wait until Travis is green :)

**Comment by Onumis** [comment]
@troessner needs a rebase again! :(

**Comment by troessner** [comment]
Rebased! I'd appreciate a speedy merge since due to the nature of this PR every single new pull request will probably introduce merge conflicts.

**Comment by Onumis** [comment]
merged!

**Pull request merged**
