### PR TITLE
Optionally ignore symlinks with -i

### PR DESCRIPTION
**Pull request by LeeXGreen**
Here's a first draft at what the functionality I outlined in #25.

### CODE REVIEW

**Comment by LeeXGreen** [comment]
I see why the Travis build failed, even though it passed on my dev machine.

I've guaranteed that only one of [original file, symlink] is processed by RubyCritic, but there's no guarantee that the original file is the one that remains. Whichever one is seen first will most likely be the winner.

**Comment by LeeXGreen** [comment]
Okay. This will now prefer files over symlinks, unless there are no real files for a given realpath. (This is a bit of a pathological case but it is possible if you have files completely external to your repo that are linked into your repo.)

This is failing a rubocop style check due to the length of https://github.com/LeeXGreen/rubycritic/blob/option_ignore_symlinks/lib/rubycritic/cli/options.rb#L11-L36 but I don't really see a sensible way to make this shorter.

**Comment by guilhermesimoes** [comment]
Looks good to me! Still, I'd like to take a better look at this by the end of the week. I know the changeset is small but bear with me.

And don't worry too much about the RuboCop checks failing. I set up RuboCop not long ago so its defaults may be a bit far from sane.

**Comment by LeeXGreen** [comment]
Sure thing -- and now that I've had a chance to sleep on this code, I think the command-line option could be better named to make it clear that it does not so much *ignore* symlinks, as *de-duplicate* them.

I especially welcome your input here.

**Comment by LeeXGreen** [comment]
Just found out this will not work properly on JRuby thanks to https://github.com/jruby/jruby/issues/538.

It should still be achievable, though -- just might require special-case behavior for JRuby.

**Comment by LeeXGreen** [comment]
Okay, this is behaviorally correct on JRuby now :)

**Comment by guilhermesimoes** [comment]
I knew I'd forgotten something last week.

Was just checking out the code when I noticed you changed this just now to work with JRuby. Here's the thing though, the previous tests were already passing on JRuby, so either it was already working or we're missing a test.

**Comment by LeeXGreen** [comment]
Aha -- it's a JRuby 1.7.9 vs 1.7.18 difference.

JRuby 1.7.9 needs the fixes in 5f3391c, whereas 1.7.18 was good with only 7447929.

Since the RubyCritic TravisCI build only runs 1.7.18, we passed with the first build.

**Comment by LeeXGreen** [comment]
To be precise, this is fixed for Jruby >= 1.7.14

**Comment by guilhermesimoes** [comment]
I see, you like to live on the edge!

A couple points before I merge though:

* In the JRuby issue you linked to, there's a reference to [this other commit][1]. And I was just wondering if there's no need to `require "java"` like it's being done there.

* Also, if you can, rename the option prefix `ignore_` to `deduplicate_`.

* And remove the shorthand option `"-i"`, just make it an empty string.

Like I said in the original issue, deduplicating paths makes too much sense to be optional but I guess we can make this a default later on.

And sorry for taking so long to check this.

[1]: https://github.com/rapid7/metasploit_data_models/commit/0b4fc033ea45309813e61446db8f10cbb18b75a1

**Comment by LeeXGreen** [comment]
Okay, your points from above are fixed:

* Not sure whether we need to `require "java"`, so I threw it in.
* it's now `deduplicate_` throughout
* `-i` option now removed.

Here is a clean commit if you prefer this one:

https://github.com/LeeXGreen/rubycritic/commit/78669f28d46057e10d842b654e4cec24e058ffa9

**Comment by guilhermesimoes** [comment]
Done! It's now on master.

Yesterday I started working on a JSON formatter which I want in the next release. So a new version should be released sometime this week when that's done.

Once again sorry for taking so long with this. Thanks! :smile:

**Pull request closed without merging**
