### PR TITLE
rubocop 0.39.0, reek 4.0.1, drop support for ruby 2.0

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by nijikon** [comment]
@troessner I assume that we want to support ruby 2.0?

**Comment by Onumis** [comment]
Official support for Ruby 2.0 ended 2 months ago, and I believe Reek v4 drops support for it as well.
With this update we should also.

**Comment by troessner** [comment]
PR and commit say "rubocop" but it upgrades Reek as well...we should fix that.

>> Official support for Ruby 2.0 ended 2 months ago, and I believe Reek v4 drops support for it as well.
With this update we should also.

Yep, good idea!

**Comment by nijikon** [comment]
@troessner changed PR subject. There are 3 commits.

**Comment by troessner** [comment]
Let's update our [compatibility](https://github.com/whitesmith/rubycritic#compatibility) section as well ;)

**Comment by nijikon** [comment]
@troessner Done.

**Comment by troessner** [comment]
Merged, thanks!

**Pull request merged**
