### PR TITLE
Bump version to 3.0.0.

### PR DESCRIPTION
**Pull request by troessner**

### CODE REVIEW

**Comment by troessner** [comment]
cc @mereghost

**Comment by Onumis** [comment]
Why not `2.10`?
There are no substantial / backwards incompatible changes right?

**Comment by troessner** [comment]
>> There are no substantial / backwards incompatible changes right?

We're dropping 2.0 support, which I'd call an incompatible change for sure :)

**Comment by Onumis** [comment]
Ah yes, you're right!

**Comment by Onumis** [comment]
Published :tada:

**Comment by troessner** [comment]
Awesome!

**Pull request merged**
