### PR TITLE
Allow Rubycritic to accept config files

### PR DESCRIPTION
**Pull request by mfbmina**
Allow Rubycritic to accept a config file instead of building the whole command through the command line.

Other tools do that, for example, Rubocop.

I need help on how I can test these changes.

### CODE REVIEW

**Comment by mfbmina** [comment]
@Onumis @lucasmazza @troessner hello! Do we still need to support old Rubies, such as Ruby 2.3 or older?

**Comment by Onumis** [comment]
@mfbmina thanks for this PR, very helpful! 

Ruby 2.3 is expected to be officially supported until March 2019, so we should too.

I guess the issue here is the `gem install bundler -v "~> 1.3"` in travis. Why is that version requirement there?

**Comment by mfbmina** [comment]
@Onumis Travis was not able to install `bundler` without this option :(

**Comment by Onumis** [comment]
@mfbmina builds should be working now, Can you rebase and push again please?

**Comment by mfbmina** [comment]
@Onumis specs are green now 😄 

Could you please let me know when is it merged and released?

**Comment by Onumis** [comment]
Merged! Will do a release later today, or tomorrow. Thanks!

**Pull request merged**
