### PR TITLE
Use RuboCop 0.51 and lint green with it

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR updates **RuboCop** to [**0.51**](https://github.com/bbatsov/rubocop/releases/tag/v0.51.0) (was 0.50).

- Lint: Use warn
- Lint: Order gem dependency lines in gemspec
- Lint: Use Time instead of DateTime - [Style Guide on this](https://github.com/bbatsov/ruby-style-guide/pull/587)
- Configuration: Enable showing RuboCop "cop names" on failing

### CODE REVIEW

**Comment by olleolleolle** [comment]
```
lib/rubycritic/source_control_systems/perforce.rb:51:9: C: Style/DateTime: Prefer Date or Time over DateTime.

DateTime.strptime(perforce_files[Perforce.key_file(path)].last_commit, '%s').strftime('%Y-%m-%d %H:%M:%S %z')

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by olleolleolle** [comment]
@Onumis There, this is ready for code review.

**Comment by Onumis** [comment]
LGTM! Just missing a line in the changelog :wink:

**Comment by olleolleolle** [comment]
@Onumis 🌮 🎉

**Pull request merged**
