### PR TITLE
Loseless image optimization

### PR DESCRIPTION
**Pull request by SuperSandro2000**
Loseless image optimization by https://imgbot.net.
*Total -- 670.74kb -> 437.32kb (34.8%)

/images/smells.png -- 117.93kb -> 73.44kb (37.72%)
/images/code.png -- 113.03kb -> 71.33kb (36.9%)
/images/smell-details.png -- 142.22kb -> 91.46kb (35.69%)
/images/reek.png -- 74.95kb -> 48.48kb (35.31%)
/images/rating.png -- 89.80kb -> 59.27kb (34%)
/images/overview.png -- 100.11kb -> 66.46kb (33.61%)
/images/churn-vs-complexity.png -- 32.70kb -> 26.87kb (17.83%)

### CODE REVIEW

**Comment by Onumis** [comment]
Neat tool! :)

**Comment by Onumis** [comment]
@SuperSandro2000 would be great if you could add yourself to the CHANGELOG.md :) 
See other PRs like this `https://github.com/whitesmith/rubycritic/pull/261/files` as an example

**Comment by SuperSandro2000** [comment]
Didn't know that. Will be doing that now and then force push.

**Comment by Onumis** [comment]
Thanks!

**Pull request merged**
