### PR TITLE
Add Support for Ruby 3.0 

### PR DESCRIPTION
**Pull request by etagwerker**
Hi there, 

This is an attempt to make RubyCritic compatible with Ruby 3.0. 

It seems that we will have to change a few dependencies: 

- SimpleCov 
- Rexml (no longer comes with Ruby) 
- Minitest 

Check list:

- [x] Add an entry to the [changelog](/CHANGELOG.md)
- [x] [Squash all commits into a single one](/CONTRIBUTING.md)
- [x] Describe your PR, link issues, etc.
- [x] Get test suite to pass with Ruby 3.0 

Please check it out and let me know what you think.

Thanks!

### CODE REVIEW

**Comment by denny** [comment]
So uh, I've been using Ruby Critic in ShinyCMS-ruby for months now, which is Rails 6.1, Ruby 3.0 project. I don't recall having to jump through many hoops, I think it all just worked - other than the simplecov thing which I did PR a tiny temporary fix for I think, just nailing down the last version that worked.

Anyway; I'm happy to test anything if that would be helpful, although as it seems to have been working for me already I'm not sure how useful I'll be! 🙂

**Comment by etagwerker** [comment]
@denny It would be great if you could review this PR. I didn't have to do any big changes, I had to explicitly declare `rexml` as a development dependency.

**Comment by denny** [comment]
> @denny It would be great if you could review this PR.

Tests all run okay for me after bundle install, except for rubcop; I'm seeing 22 offences there. I _think_ they're mostly easy ones, there's a lot of 'call super here' and 'use e not err or error' in the mix.

**Comment by denny** [comment]
[rubocop.log](https://github.com/whitesmith/rubycritic/files/6217800/rubocop.log)

**Review by nunosilva800 — APPROVED** [review]
Looks good, thanks! 🎉

**Comment by etagwerker** [comment]
@denny Thanks for looking into this PR! That's weird. Not sure what that is about. When I run it in my local environment I don't see any offenses. 

```
$ bundle exec rubocop
Inspecting 115 files
...................................................................................................................

115 files inspected, no offenses detected
$ bundle exec rubocop --version
0.65.0
```

Maybe it is happening in your local env because you are running a more recent `rubocop`? 

@nunosilva800 Thanks for your review! 💯

**Comment by denny** [comment]
Ah. Tiny bit more recent, yes:
```bash
denny@rocinante:~$ rubocop --version
1.12.0
```

**Pull request merged**
