### PR TITLE
Upgrade to reek 5.0.2 (whitesmith#269)

### PR DESCRIPTION
**Pull request by taitran19**
- Change .todo.reek.yml to .reek.yml
- Remove unparsable file and related specs because unparsable file
will throw error instead of show it in report
- Configure fakefs to clone reek schema file because this file is required to init reek

### CODE REVIEW

**Comment by n-rodriguez** [comment]
Hi there! It could be the occasion to upgrade `TTY::Which` to the latest version (0.4.0). What do you think?

**Comment by Onumis** [comment]
It probably is best to keep this PR focused on Reek. 
@taitran19 could you rebase this?
Not sure why the CI didn't run :thinking:

**Comment by taitran19** [comment]
@n-rodriguez: It would be better to upgrade `TTY::Which` in another PR

@Onumis: I have rebased my PR, but it can't build on Travis CI because it is reported as `Abuse detected`. Can you email to support@travis-ci.com to check the reason and post it here so that I can fix in case needed?

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by Onumis** [comment]
@taitran19 

> It seems that the PR you linked was marked as Potential Abuse due to the fact the the submitter changed their Github username in the meantime.
> I've removed the flag so could you please try and trigger a new build for the PR and let us know if it works?

Can you? I still can't see it on travis: https://travis-ci.org/whitesmith/rubycritic/pull_requests

**Comment by taitran19** [comment]
@Onumis: I have rebased from master and pushed again. CI has been built but the build has been failed. That is because reek v5.x only support ruby version >= 2.3. It means if we want to upgrade reek, we have to drop support for ruby 2.1 and 2.2. What do you think?

**Comment by Onumis** [comment]
I think it's about time! :smile:

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by taitran19** [comment]
Ruby 2.2.x are not maintained anymore. Should we drop them from travis.yml?

**Comment by n-rodriguez** [comment]
> I think it's about time! smile

Hi there! Any news?

**Comment by n-rodriguez** [comment]
> Ruby 2.2.x are not maintained anymore. Should we drop them from travis.yml?

Note that Ruby 2.3 is EOL in march.

**Comment by Onumis** [comment]
Yep, still we should do a release that drops 2.1 and 2.2 before dropping 2.3

#290 did that. will merge this soon

**Pull request merged**
