### PR TITLE
Drop support for 2.6.x

### PR DESCRIPTION
**Pull request by faisal**
Closes https://github.com/whitesmith/rubycritic/issues/441

Check list:
- [X] Add an entry to the [changelog](https://github.com/whitesmith/rubycritic/blob/main/CHANGELOG.md)
- [x] [Squash all commits into a single one](https://github.com/whitesmith/rubycritic/blob/main/CONTRIBUTING.md)
- [x] Describe your PR, link issues, etc.

### CODE REVIEW

**Comment by faisal** [comment]
As an aside, [Ruby 2.7 is EOL now](https://www.ruby-lang.org/en/news/2023/03/30/ruby-2-7-8-released/) as well. Would it be better to jump straight to a 3.0 minimum Ruby?

**Comment by faisal** [comment]
@nunosilva800 can you approve the workflow?

**Comment by faisal** [comment]
I tested the prior commit against ruby (3.2), ruby@3.1, ruby@3.0, ruby@2.7, and jruby@9.4. I wasn't able to test against jruby 9.3, as it's no longer available as a formula. @nunosilva800 can you please approve the workflow to confirm results?

FWIW this was the minimum rubocop that got things working for all the above Ruby versions. I did also try bumping rubocop to the current version (1.50.2), but it threw 20 additional warnings (most of which couldn't be auto-corrected), and wants us to enable or disable new warnings. I'd like to open new PRs to update rubocop and other dependencies to more recent versions,  but those are separate conversations.

**Comment by faisal** [comment]
Notes:
- Jruby 9.3 is Ruby 2.6. As part of dropping Ruby 2.6 support we should drop Jruby 9.3 as well. Who can do so?
- Reek and Rubocop are fighting over whether exception errors should or should not be named 'e'. I'll try to come to a sensible answer on that.
- Reek is throwing a number of other warnings that I will dig in on when I have a chance. It seems like we silence its (and rubocop's) output a lot, so is there any guidance on when is appropriate to do so?

**Comment by faisal** [comment]
I believe the prior commits address the three issues named in the prior three commits. I've manually run `bundle exec rake` (or `jbundle exec jrake`) across all rubies. This time with feeling?

@nunosilva800 are you the appropriate reviewer here, once workflows pass?

**Comment by faisal** [comment]
If it's better to drop 2.7 support and jump straight to Ruby 3, then I can pull all these changes in as well: https://github.com/faisal/rubycritic/tree/ruby_3

**Comment by faisal** [comment]
Squashed to one commit. @nunosilva800 (or other maintainer) please unlock the workflow if this looks satisfactory. 

Alternatively, please let me know if you'd rather we drop 2.7 as well, and jump directly to Ruby 3.

**Review by nunosilva800 — APPROVED** [review]
LGTM! Removing ruby 2.6 only is fine for now. Better to be step by step. We can cut a release for this version, before dropping 2.7.

**Comment by faisal** [comment]
> LGTM! Removing ruby 2.6 only is fine for now. Better to be step by step. We can cut a release for this version, before dropping 2.7.

SGTM. What do expect for timeframe for this release?

And what's the next step for merging this PR?

**Comment by nunosilva800** [comment]
I think this is good to go. I'll do a release following the merge.

**Pull request merged**
