### PR TITLE
RuboCop Auto Correct: Sytle/SpecialGlobalVars

### PR DESCRIPTION
**Pull request by ericboehs**

### CODE REVIEW

**Comment by ericboehs** [comment]
It seems the auto correct for `$?` doesn't work for our scenario. Should I add instead add the TODO to our permanent ignore list?

**Comment by Onumis** [comment]
@ericboehs Hi! Thanks for the contribution.
As a general note, you should reference the originating issue you are solving (in this case #250), and provide a brief description ;)

-----

You can make this work by adding a `require 'English'`.
You can place it in `lib/rubycritic/source_control_systems/base.rb`, right before `require 'shellwords'`.

Rubocop warns it when you run the autocorrect:
```
[Corrected] Prefer $CHILD_STATUS from the stdlib 'English' module (don't forget to require it) over $?.
```

See also: 
- https://ruby-doc.org/core-2.4.0/Process/Status.html
- http://ruby-doc.org/stdlib-2.4.0/libdoc/English/rdoc/English.html

Additionally, please add an entry to `CHANGELOG.md` on the unreleased section (at the top).

**Comment by olleolleolle** [comment]
@ericboehs Hi! Do you still wish to make the suggested changes?

If yes, just commit more changes to this branch. If not, say the word, and we'll pick it up and carry it through.

Thanks again for making a contribution!

**Comment by Onumis** [comment]
closing due to inactivity

**Pull request closed without merging**
