### PR TITLE
Update jruby CI configuration

### PR DESCRIPTION
**Pull request by etagwerker**
Check list:
- [ ] Add an entry to the [changelog](https://github.com/whitesmith/rubycritic/blob/main/CHANGELOG.md)
- [x] [Squash all commits into a single one](https://github.com/whitesmith/rubycritic/blob/main/CONTRIBUTING.md)
- [x] Describe your PR, link issues, etc.

I'm pretty sure RubyCritic no longer works with jruby-9.2 due to recent required ruby version changes to the gem's configuration. So this is an attempt to update jruby's configuration (experimental) in CI.

### CODE REVIEW

**Comment by h-r-k-matsumoto** [comment]
Hi @etagwerker ,
Sorry if I might be rude.
You faced the following problem.
https://github.com/jruby/jruby/issues/7735

This is a problem of JRuby or fakefs, but we can resolve it with following patch.
https://github.com/h-r-k-matsumoto/rubycritic/commit/b1d6035eb58b75ae432fb1964122d99d5dcf9556
https://github.com/h-r-k-matsumoto/rubycritic/actions/runs/4520028160

**Comment by etagwerker** [comment]
@h-r-k-matsumoto Thanks for that patch, it totally worked! 

Do you think that should be a patch submitted to `fakefs` itself?

**Comment by h-r-k-matsumoto** [comment]
@etagwerker Thanks for your reply.

> Do you think that should be a patch submitted to `fakefs` itself?

It's hard to answer...
But I'm afraid that my answer is No.
It's because that the root cause of this problem is `JRuby` so users should upgrade `JRuby`.
And more, I don't know `fakefs` support `JRuby` or not.

But using the version of `fakefs` with `rubycritic` is a bit old in order to supporting the old Ruby version.
In that case, we have to address on the issue individually.

This is my opinion.

**Comment by etagwerker** [comment]
@h-r-k-matsumoto got it, thank you!

**Pull request merged**
